% This function mxNiDeleteContext, closes the Kinect-objects which connect
% to the Kinect streams, such as image, IR and depth. 
%
% mxNiDeleteContext(KinectHandles);
%
% inputs,
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxNiCreateContext, such as main, image, IR, Depth and User node.
%
% See also mxNiCreateContext, mxNiUpdateContext, mxNiDepth, mxNiPhoto,
%		mxNiInfrared, mxNiSkeleton, compile_cpp_files
%
% Mex-Wrapper is written by D.Kroon Focal 2.0 (June 2013)  

